services:
  todo-api:
    build: .
    container_name: todo-api
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: nouchka/sqlite3:latest
    container_name: db
    volumes:
      - db_data:/app/database.db
    restart: always

volumes:
  db_data:
